### ISSUE TITLE
Database directory lineedit is buggy

### ISSUE THREAD

**Issue by ebrahimebrahim** [OpenwaterHealth/SlicerOpenLIFU#94]
Pressing enter in database directory lineedit doesn't work. I get:

```
Exception raised in onLoadDatabaseClicked: onLoadDatabaseClicked() missing 1 required positional argument: 'checked'
```

Also the file dialog on the ctk lineedit appears to be looking for files not directories. weird

**Comment by ebrahimebrahim** [comment]
From a bisect on file dialog bug:
> b717911addd0e4d2bb597694de79557bc4cd1253 is the first bad commit
