### ISSUE TITLE
Incomplete restructuring of OpenLIFULib

### ISSUE THREAD

**Issue by ebrahimebrahim** [OpenwaterHealth/SlicerOpenLIFU#90]
Bug introduced in #88 due to the file restructuring
When I open the openlifu home module, I get

```
Traceback (most recent call last):
  File "/home/ebrahimebrahim/openwater/SlicerOpenLIFU/build/lib/Slicer-5.7/qt-scripted-modules/OpenLIFUHome.py", line 104, in setup
    self.updateInstallButtonText()
  File "/home/ebrahimebrahim/openwater/SlicerOpenLIFU/build/lib/Slicer-5.7/qt-scripted-modules/OpenLIFUHome.py", line 128, in updateInstallButtonText
    if OpenLIFULib.python_requirements_exist():
AttributeError: module 'OpenLIFULib' has no attribute 'python_requirements_exist'
```
